### ISSUE TITLE
DELETE record from GreptimeDB

### ISSUE THREAD

**Issue by yuanbohan** [GreptimeTeam/greptimedb-ingester-go#20]
delete specified row(s) from GreptimeDB

## Field in Proto file

[database.proto](https://github.com/GreptimeTeam/greptime-proto/blob/main/proto/greptime/v1/database.proto#L43)

## Java Example

[quick start](https://github.com/GreptimeTeam/greptimedb-ingester-java/blob/main/ingester-example/src/main/java/io/greptime/LowLevelApiWriteQuickStart.java#L88-L95), but ingester-go should keep go convention

**Comment by JetSquirrel** [comment]
I'd like to try this, please assign to me. Thank you.

**Comment by tisonkun** [comment]
@JetSquirrel Thanks for your application! I'm glad to assign this issue to you.

To be clear that we can make some progress, what's your plan on resolving this issue, or what the information you'd like to know before you can work on this issue.

**Comment by JetSquirrel** [comment]
Thanks for @tisonkun and @yuanbohan , I actually finished this work, but I need discuss and cofirme my resolution is good.

I reference the java version [quick start](https://github.com/GreptimeTeam/greptimedb-ingester-java/blob/main/ingester-example/src/main/java/io/greptime/LowLevelApiWriteQuickStart.java#L88-L95), but I choose create another function to replace `WriteOp` parameter:
```golang
resp, err = client.Delete(context.Background(), table)
```
In the function `Write()/Delete()` in client, it's call anthoer function `write()`
```golang
func (c *Client) Write(ctx context.Context, tables ...*table.Table) (*gpb.GreptimeResponse, error) {
	return c.write(ctx, types.Insert, tables...)
}

func (c *Client) Delete(ctx context.Context, tables ...*table.Table) (*gpb.GreptimeResponse, error) {
	return c.write(ctx, types.Delete, tables...)
}
```

and the `write()` function is same [Write()](https://github.com/GreptimeTeam/greptimedb-ingester-go/blob/08930f5fcbe12870298772999796dd4884139e8f/client.go#L65-L72)

```golang
func (c *Client) write(ctx context.Context, writeOp types.WriteOp, tables ...*table.Table) (*gpb.GreptimeResponse, error) {
	...
	request_, err := request.New(header_, tables...).Build(writeOp)
        ...
}
```
I worte unit test for `Delete` functions, and passed the test.

Please mentor me how to cotribute better and imporve my code, many thanks.
[JetSquirrel/greptimedb-ingester-go@delete-record](https://github.com/JetSquirrel/greptimedb-ingester-go/tree/delete-record)

**Comment by yuanbohan** [comment]
I have read your codes in delete-record branch, and I think it's good enough to commit a Pull Request to the upstream. 

Thanks for your contribution, and I will leave my comments on the PR.

**Comment by JetSquirrel** [comment]
Thank you, I created PR #29, pls help me to review.
