### ISSUE TITLE
Support set timezone when config a new connection

### ISSUE THREAD

**Issue by Taylor-lagrange** [GreptimeTeam/greptimedb-ingester-go#28]
GreptimeDB already support set timezone in gRPC protocol, to specify some default behavior when insert and query data, but `greptimedb-ingester-go` seem still not support set timezone when build a new connection

**Comment by yuanbohan** [comment]
timezone is unnecessary in writing scenario, and ingester in only for writing, updating and deleting. So I will close this issue cc @waynexia
