### ISSUE TITLE
Panic in CloseStream

### ISSUE THREAD

**Issue by cedws** [GreptimeTeam/greptimedb-ingester-go#36]
https://github.com/GreptimeTeam/greptimedb-ingester-go/blob/11097663940c13f4ab69148e145cfb0be6caeb13/client.go#L271-L282

`CloseStream` may attempt to use `c.stream` when it is nil, which happens if a stream has not previously been written to.

**Comment by evenyag** [comment]
Thanks for your report, this should be a bug. Would you be interested in submitting a PR to fix it? @cedws

**Comment by evenyag** [comment]
https://github.com/GreptimeTeam/greptimedb-ingester-go/pull/37 should fix this.
