### ISSUE TITLE
Supports gRPC write hints

### ISSUE THREAD

**Issue by killme2008** [GreptimeTeam/greptimedb-ingester-go#40]
Just like java sdk

https://github.com/GreptimeTeam/greptimedb-ingester-java/pull/43

https://github.com/GreptimeTeam/greptimedb-ingester-java/pull/44

Users can set custom table options as write hints when automatically creating tables:

* `append_mode`
* `ttl`
* `merge_mode`

**Comment by daviderli614** [comment]
Usage Examples：https://github.com/GreptimeTeam/greptimedb-ingester-go/blob/b07ec74f356ce7e853bc18664e0bdb42b6b64404/examples/hint/main.go#L93
```
hints = append(hints,
  hint.Hint{Key: "ttl", Value: "3d"},
  hint.Hint{Key: "merge_mode", Value: "last_non_null"},
  hint.Hint{Key: "append_mode", Value: "false"},
)
```
